FROM ghcr.io/gbraad-devenv/ubi8-gotoolset/base:1.22

USER root

RUN dnf install -y \
        https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm \
    && dnf install -y \
        powerline \
        vim-powerline \
        stow \
    && dnf clean all \
    && rm -rf /var/cache/yum

USER gbraad
ENV HOME=/home/gbraad

RUN git clone https://github.com/gbraad/dotfiles ~/.dotfiles \
    && ~/.dotfiles/install.sh